version: '3.8'

services:
  fastapi_backend:
    build: .
    container_name: fastapi_backend_container
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  telegram_bot:
    build: .
    container_name: telegram_bot_container
    command: python bot_main.py
    volumes:
      - .:/app
    depends_on:
      - fastapi_backend
    env_file:
      - .env

  tests:
    build: .
    container_name: tests_container
    volumes:
      - .:/app
    depends_on:
      fastapi_backend:
        condition: service_started
    env_file:
      - .env
    command: >
      /bin/sh -c "sleep 5 && pytest test_api.py"